### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by paskal** [jtaczanowski/go-graphite-client#1]
Hi @jtaczanowski, thanks a lot for your library! I've seriously thought about writing my own because all existing libraries either don't care about persistent connection or ask you to call connect/disconnect every time. Your approach is elegant and I will use it instead.

**Comment by jtaczanowski** [comment]
Hi @paskal , It nice to hear that this code fits your needs:)

But I want to notice that the library is creating new connection before sending every metrics set. For example if you sending set of 100 metrics every minute, this 100 metrics will be send in single connection. But in next minute, before sending next set of 100 metrics new connection will be created.

There is possible to maintain one persistent connection for all the time, but in this case I think it is not necessary.

**Comment by paskal** [comment]
I'm okay with it, I think maybe we should stress this point in the readme because module users really should not send metrics one by one, but should instead send them in batches.

Maintaining connections increase complexity, I am willing to pay the price of complexity combining metrics on my side instead.

**Comment by jtaczanowski** [comment]
I updated readme and mentioned about collecting metric in batch, before sending it.

Exactly, in the past I have case when creating Logstash client. Logstash server was dropping TCP connection every few seconds. The logic responsible for detecting connections drops and restablishing connection which I had to implement in client has become quite complicated.

**Comment by paskal** [comment]
By the way, I noticed that having `[]map[string]float64` for metrics is overkill because they really would be expanded to `map[string]float64`, and there is no point of sending metric with same name multiple times.

Why this library uses an array instead of a map?

**Comment by jtaczanowski** [comment]
Hmm, you are correct, there is no need to wrap ```[]map[string]float64``` into list. I will create PR changing this behavior.

**Comment by jtaczanowski** [comment]
Please for review https://github.com/jtaczanowski/go-graphite-client/pull/3 :)
